package viewer;


import controller.DifficultyEnum;
import viewer.ControllerFacade;
import controller.DifficultyEnum;
import game.NotFoundException;
import viewer.GameBoardFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Eman
 */
public class DifficultySelectionFrame extends javax.swing.JFrame {
    private ControllerFacade controller;

    /**
     * Creates new form DifficultySelectionFrame
     */
    public DifficultySelectionFrame(ControllerFacade controller) {
        this.controller = controller;
        initComponents();
        setLocationRelativeTo(null); // Center on screen
        setTitle("Sudoku - Select Difficulty");
    }
        private void loadGameByDifficulty(char level, DifficultyEnum difficulty) {
        try {
        // Clear the undo log before loading a new game
        controller.clearLog();
        
        // Load game using ControllerFacade
        int[][] board = controller.getGame(level);
        
        // Close this frame
        this.dispose();
        
        // Show game board
        GameBoardFrame gameFrame = new GameBoardFrame(board, controller, difficulty);
        gameFrame.setVisible(true);
        
    } catch (NotFoundException e) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Game not found: " + e.getMessage(),
            "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Error loading game: " + e.getMessage(),
            "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnEasy = new javax.swing.JButton();
        btnMedium = new javax.swing.JButton();
        btnHard = new javax.swing.JButton();
        btnback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("    Select Difficulty Level");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 22, 226, 27));

        btnEasy.setBackground(new java.awt.Color(51, 204, 0));
        btnEasy.setText("Easy");
        btnEasy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEasyActionPerformed(evt);
            }
        });
        getContentPane().add(btnEasy, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 80, 38));

        btnMedium.setBackground(new java.awt.Color(255, 255, 0));
        btnMedium.setForeground(new java.awt.Color(51, 51, 0));
        btnMedium.setText("Medium");
        btnMedium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMediumActionPerformed(evt);
            }
        });
        getContentPane().add(btnMedium, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 80, 40));

        btnHard.setBackground(new java.awt.Color(255, 0, 0));
        btnHard.setText("Hard");
        btnHard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHardActionPerformed(evt);
            }
        });
        getContentPane().add(btnHard, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 80, 40));

        btnback.setBackground(new java.awt.Color(255, 255, 0));
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        getContentPane().add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEasyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEasyActionPerformed
       loadGameByDifficulty('e', DifficultyEnum.EASY);  // TODO add your handling code here:
    }//GEN-LAST:event_btnEasyActionPerformed

    private void btnMediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMediumActionPerformed
        loadGameByDifficulty('m', DifficultyEnum.MEDIUM); // TODO add your handling code here:
    }//GEN-LAST:event_btnMediumActionPerformed

    private void btnHardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHardActionPerformed
       loadGameByDifficulty('h', DifficultyEnum.HARD); // TODO add your handling code here:
    }//GEN-LAST:event_btnHardActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
this.dispose();  
new WelcomeFrame().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnbackActionPerformed

    /**
     * @param args the command line arguments
     */
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DifficultySelectionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DifficultySelectionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DifficultySelectionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DifficultySelectionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEasy;
    private javax.swing.JButton btnHard;
    private javax.swing.JButton btnMedium;
    private javax.swing.JButton btnback;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
