package viewer;


import viewer.ControllerFacade;
import controller.DifficultyEnum;
import game.NotFoundException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Eman
 */
public class StartupFrame extends javax.swing.JFrame {
    private ControllerFacade controller;

    /**
     * Creates new form StartupFrame
     */
    public StartupFrame() {
        initComponents();
        this.setVisible(false);
        this.controller = new ControllerFacade();
        handleStartup();
        
    }
        private void handleStartup() {
        try {
            // Get catalog from backend using ControllerFacade
            boolean[] catalog = controller.getCatalog();
            
            boolean hasCurrentGame = catalog[0];  // [0] = has incomplete game
            boolean allModesExist = catalog[1];   // [1] = all difficulty levels exist
            
            if (hasCurrentGame) {
                // Load the incomplete/current game
                loadCurrentGame();
            } else if (allModesExist) {
                // Show difficulty selection screen
                showDifficultySelection();
            } else {
                // Show file upload screen
                showFileUploadScreen();
            }
            
            this.dispose(); // Close this control frame
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(null,
                "Startup Error: " + e.getMessage(),
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            System.exit(1);
        }
    }
    private void loadCurrentGame() {
        try {
            // Load current game using 'c' for CURRENT
            int[][] board = controller.getGame('c');
            
            // Show the game board
            GameBoardFrame gameFrame = new GameBoardFrame(board, controller, DifficultyEnum.CURRENT);
            gameFrame.setVisible(true);
            
        } catch (NotFoundException e) {
            javax.swing.JOptionPane.showMessageDialog(null,
                "Error loading current game: " + e.getMessage(),
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            showDifficultySelection();
        }
    }

    private void showDifficultySelection() {
        DifficultySelectionFrame diffFrame = new DifficultySelectionFrame(controller);
        diffFrame.setVisible(true);
    }

    private void showFileUploadScreen() {
        FileUploadFrame uploadFrame = new FileUploadFrame(controller);
        uploadFrame.setVisible(true);
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sudoku Startup");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartupFrame();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
